### ISSUE TITLE
simplified snapshot filename (and in the same directory)

### ISSUE THREAD

**Issue by albanlusitanae** [bog-dan-ro/spectacol#123]
Saving the snapshot into a single directory folder, under the filename syntax [name]_[yyyymmdd]_[hhmmss]. Example: wizball_20160901_103422

**Comment by bog-dan-ro** [comment]
That was the first behavior but I didn't like it because during the game you can have multiple snapshots and you can go back to any of them ... now imagine that you are playing 10 games and for each you have 10 snapshots :) it will be quite hard to browse all of them :)

Anyway the new format that I proposed on #34 will fix this problem because all the snapshots/rzx(s) will be saved in the same .zx file.

Duplicate #34
