### ISSUE TITLE
Port to Retroarch ?

### ISSUE THREAD

**Issue by ghost** [bog-dan-ro/spectacol#147]
@bog-dan-ro This emulator is fantastic ! Is there any chance of you porting this to Retroarch ? The current FUSE version is very primitive (v1.1 I think) and the current "maintainer" just ignores everything. I'm not sure if he's been busy for years or left the project completely, nobody has taken over. I guess the ZX Spectrum is one of the least popular cores.

**Comment by bog-dan-ro** [comment]
Retroarch and spectacol are "competitive" solutions, it will be close to impossible to port spectacol to retroarch. What somebody can do is to take my fuse version and port that to retroarch.

I created Spectacol because none of the existing emulators were good enough for me, personally I don't have any plans nor time to port a newer fuse version to retroarch.
