### ISSUE TITLE
Download only selected games

### ISSUE THREAD

**Issue by maverick74** [bog-dan-ro/spectacol#29]
I would like the possibility to download only the selected games instead of all the visible ones presented on screen.

**Comment by bog-dan-ro** [comment]
I already fixed that problem by copying the selected files from "Downloaded" to Favourites folder #19 . #21 allows you to delete files/folders.
I'm caching all the files in Downloaded, because in order to show you the screen I need to download the entire game (most of the time, the .png screen image is larger than the  entire .z80 file), therefore it will be a waste of internet bandwidth to not cache them all. Of course second time when you search for these games , I'll not download them again.

**Comment by maverick74** [comment]
I see... And what about jpg or gif? Wouldn't they be lite?

**Comment by bog-dan-ro** [comment]
Just a little bit little than the game file ..
