### ISSUE TITLE
Turn off the left drawer menu opening by swipe gesture on small screen devices

### ISSUE THREAD

**Issue by bog-dan-ro** [bog-dan-ro/spectacol#41]
As I could see in this https://www.youtube.com/watch?v=W-6rGIkfKsw video some time is quite annoying.

**Comment by ZxAsSeMbLeR** [comment]
I have tried your new version (2.0 Alpha) and the stretching option is working perfect!. Thanks!!
The only drawback is similar as in this video (the screen is not stretched in the left side but it is in the right). In the video the left side is bigger than the right side, and after stretching the black border on the right side dissapears but on the left side is still there (reduced). In an Android tablet it is working ok, in an Android TV is also working, but in two smartphones I have tried the left border is still there (Xiaomi Redmi 3 and Lenovo K3 Note). I don't know if it is happening when the screens are smaller (such as in Smartphones). Maybe this is related to this bug, so I am commenting here instead of in the closed scaling feature. Before scaling the screen was exactly as in this video in the smartphones but was looking centered and much better in bigger screens.

Thank you!

**Comment by bog-dan-ro** [comment]
The left border is added **only** on small screen devices (height or width is less than 80mm) in **landscape** mode, because the virtual joystick covers way too much of the screen.
I tried to play lots of games on my phone and the only way to be able to play them was to add an 1cm left margin, so, I'd like to keep it as it is.

This bug is about not allowing on small screen devices the drawer menu to be opened using the swipe gesture on the left side.

**Comment by ZxAsSeMbLeR** [comment]
Ok, maybe that's because I am used to play emus without a left border, even if the virtual gamepad is on the screen just to have the game using all the screen. Anyway, stretching the screen is a very nice improvement, so don't misunderstand me...I am really happy with how it looks now. Obviously I would prefer the 1 cm left border would be optional in smartphones, but I understand it is a matter of taste ;-)

Thanks for clarying this bug and keep up the good work!
