### ISSUE TITLE
Online grid view is very ugly on small screen devices

### ISSUE THREAD

**Issue by bog-dan-ro** [bog-dan-ro/spectacol#66]
Check #18

**Comment by ghost** [comment]
I assumed it worked fine on everyone else's because nobody else reported anything.

**Comment by bog-dan-ro** [comment]
Or nobody cared to report it ;-)

**Comment by bog-dan-ro** [comment]
What kind device do you have? A gsmarena link will be quite useful.

**Comment by ghost** [comment]
GPD XD. It's a portable Android gaming device.

http://www.gpdxd.com/

They are not on gsmarena. I got mine from an eBay shop £132 (32GB version).

One thing that bugs me about Android is that it's 60Hz so when using PAL emulators they don't look very good. On my old Nintendo DS Lite the Spectrum emulator ZXDS (Best Spectrum emulator ever made) plays everything smoothly. You can easily see the difference on horizontal scrolling text. It's perfectly smooth on ZXDS so I don't know what the refresh rate is or how he did it. On any Android emulator it's jerky.

**Comment by bog-dan-ro** [comment]
This device is not the worst out there ... is not nvidia Shield, but still it has pretty decent specs.
I'm using Spectacol on a few Android devices, a phone, a tablet and on an nvidia shield TV (well, the specs of this devices are pretty high) and I'm quite pleased about the speed.

**Comment by ghost** [comment]
I never said it was the worse, i'm quite happy with it. I also have a TV device and a tablet that both have Tegra 4 chips, yes they are quite powerful but they stutter more than the Mali. The thing about nVidia is that they overclock and burn the chip to hell to get it to do what they claim, the Mail T764 doesn't even get warm.

All Android devices display PAL badly because of the 60Hz refresh rate.

**Comment by bog-dan-ro** [comment]
Well Spectacol (or any QML application) _should_ run at 60 FPS easily, of course if the hardware is powerful enough...

**Comment by ghost** [comment]
Sorry, I think you missed my point. ZX Spectrum is a PAL computer so it's supposed to run at 50fps (50Hz). Because the Android operating system runs everything at 60Hz (60fps) then PAL emulators will have micro stutter. You can notice this on anything that scrolls horizontally. This also happens on C64 and Amiga emulators on Android. That's why the Raspberry Pi has become so popular for emulators because it can display at 50hz/60hz which means perfectly smooth scrolling on PAL or NTSC.
