### ISSUE TITLE
Snapshot joystick prompt when loading RZX

### ISSUE THREAD

**Issue by ghost** [bog-dan-ro/spectacol#69]
When the 'Snapshot joystick prompt' is enabled, when loading RZX files the joystick select menu comes up which isn't needed for playing RZX files.

**Comment by bog-dan-ro** [comment]
Well some RXZ files have snapshots, I'll check with upstream

**Comment by bog-dan-ro** [comment]
It will be useful a RZX which doesn't have snapshot but which shows the joystick selection dialog

**Comment by ghost** [comment]
What I meant was, RZX files are for watching only so a joystick prompt seems a bit pointless. No bother, I can just turn off the 'Snapshot joystick prompt'.

**Comment by bog-dan-ro** [comment]
It's not true :) RZX files with snapshots can be replayed and i.e. press a key you can continue **playing** the game from that point ;-).
If your RXZ has snapshot support, it will prompt for a joystick, otherwise it should not, this is why it will be great if you'll share one of these RZX to check it properly.

**Comment by ghost** [comment]
OK, I'll close this then. I've turned off the joystick prompt as I have no use for it.
